# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Poiss <- function(m, x) {
    .Call(`_MMPPsampler_Poiss`, m, x)
}

discsamp <- function(p) {
    .Call(`_MMPPsampler_discsamp`, p)
}

Fast_Matrix_exponential <- function(Q, Lambda, Inter, M2, pp = 10L, msg = FALSE) {
    .Call(`_MMPPsampler_Fast_Matrix_exponential`, Q, Lambda, Inter, M2, pp, msg)
}

Forward_Accumulation_cpp <- function(y_0Tprime, Inter, Q, Lambda, Rho, pp = 12L, messages = TRUE) {
    .Call(`_MMPPsampler_Forward_Accumulation_cpp`, y_0Tprime, Inter, Q, Lambda, Rho, pp, messages)
}

Interval_sampling_accumulation_cpp <- function(x_0T, y_0Tprime, Inter, Q, Lambda, pp = 12L, messages = TRUE) {
    .Call(`_MMPPsampler_Interval_sampling_accumulation_cpp`, x_0T, y_0Tprime, Inter, Q, Lambda, pp, messages)
}

Z_Sampling_cpp <- function(y_0Tprime, path_x, path_t, Inter, Lambda_Z, Lambda, messages = TRUE) {
    .Call(`_MMPPsampler_Z_Sampling_cpp`, y_0Tprime, path_x, path_t, Inter, Lambda_Z, Lambda, messages)
}

